source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

target 'YapDatabaseExtensions' do
  pod 'YapDatabase'
  pod 'PromiseKit/Swift/Promise', '~> 2'
  pod 'BrightFutures', '~> 1.0'
  pod 'SwiftTask', '~> 3'
end

target 'YapDatabaseExtensionsTests' do
  pod 'YapDatabase'
  pod 'PromiseKit/Swift/Promise', '~> 2'  
  pod 'BrightFutures', '~> 1.0'  
  pod 'SwiftTask', '~> 3'  
end

