platform :ios do

  before_all do |lane|
    carthage platform: 'iOS'
  end

  desc "Runs all the tests"
  lane :test do

    scan(
      scheme: 'YapDatabaseExtensions',
      output_directory: ".ci/xcodebuild-data",
      destination: "platform=iOS Simulator,OS=11.1,name=iPhone 7"
    )

  end

end

platform :mac do

  before_all do |lane|
    carthage platform: 'Mac'
  end

  desc "Runs all the tests"
  lane :test do

    scan(
      scheme: 'YapDatabaseExtensions',
      output_directory: ".ci/xcodebuild-data",
      destination: "platform=OS X"
    )

  end

end
