platform :ios do

  before_all do |lane|
    carthage platform: 'iOS'
  end

  desc "Runs all the tests"
  lane :test do
        
    scan(
      scheme: 'YapDatabaseExtensions-iOS', 
      output_directory: ".ci/xcodebuild-data",
      xcargs: "-derivedDataPath .ci/xcodebuild-data"
    )

  end
  
end

platform :mac do

  before_all do |lane|
    carthage platform: 'Mac'
  end

  desc "Runs all the tests"
  lane :test do
        
    scan(
      scheme: 'YapDatabaseExtensions-OSX', 
      output_directory: ".ci/xcodebuild-data",
      xcargs: "-derivedDataPath .ci/xcodebuild-data"
    )

  end
  
end
