#!/usr/bin/env bash
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby ruby
bundle install --quiet
bundle exec slather coverage --scheme "YapDatabaseExtensions-iOS" --buildkite --coveralls --build-directory .ci/xcodebuild-data